### PR TITLE
Fix for #3, adding compatibility for 11ty v1.x: Overriding error listener at instance level instead of statically.

### PR DESCRIPTION
**Pull request by patricknelson**
Fix for #3, does two things:

1. Adding compatibility for 11ty v1.x: Overriding error listener at instance level instead of statically.
2. Also resetting error state after displaying. Piggybacking this for better compatibility for rendering errors that may be trigged by other build processes (but still able to call the `EleventyErrorHandler.error` handler).

Let me know if you'd prefer to break out the `errorToShow` state cleanup to a separate PR (or rip it out completely). For me it was problematic when I was trying to hook into this to render SASS compilation errors but they wouldn't clear out since the build watches/refreshes separately which won't clear the internal state of this particular plugin (which will perpetually show this error until the next 11ty watch event gets triggered).

You can install and test it via:

```
npm i "https://github.com/patricknelson/eleventy-plugin-error-overlay.git#fix-11ty-v1.0.0"
```

### CODE REVIEW

**Comment by stevenpetryk** [comment]
Let's give it a whirl! I'll release it. Thanks for this.

**Comment by stevenpetryk** [comment]
Released as v1.0.0.

**Comment by patricknelson** [comment]
Awesome, made it into v1 baby!

**Comment by patricknelson** [comment]
Hah, actually looks like there's already a 1.0.2 so I suppose this should be 1.0.3 😬

The v1.0.0 was in reference to 11ty itself, not this particular plugin.

**Pull request merged**
